version: "3.7"

networks:
  front-tier:
  back-tier:

volumes:
  alertmanager-data: {}
  prometheus-data: {}
  grafana-data: {}
  
services:

  # SERVICIO DE GRAFANA
  grafana:
    container_name: grafana
    image: grafana/grafana:11.0.0
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana-data/:/etc/grafana/provisioning/
      - grafana-data:/var/lib/grafana
    networks:
      - back-tier
      - front-tier
    restart: always

  # SERVICIO DE PROMETHEUS
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.34.0
    volumes:
      - ./prometheus-data/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - alertmanager:alertmanager
    networks:
      - back-tier
    restart: always

  # SERVICIO DE NODE-EXPORTER
  node-exporter:
    container_name: node-exporter
    image: quay.io/prometheus/node-exporter:latest
    pid: host
    command: 
      - '--path.rootfs=/host'
    #   - '--path.procfs=/host/proc' 
    #   - '--path.sysfs=/host/sys'
    #   - --collector.filesystem.ignored-mount-points
    #   - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    network_mode: host
    networks:
      - back-tier
    restart: always
    volumes:
    #   - /proc:/host/proc:ro
    #   - /sys:/host/sys:ro
    #   - /:/rootfs:ro
      - /:/host:ro,rslave

  # ALERTAS DE PROMETHEUS
  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:v0.23.0
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager-data/:/etc/alertmanager/
    networks:
      - back-tier
    restart: always
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
  
  # SERVICIO CADVISOR: PARA MONITOREAR CONTENEDORES
  cadvisor:
    container_name: cadvisor
    image: google/cadvisor:v0.33.0
    # volumes:
    #   - /:/rootfs:ro
    #   - /var/run:/var/run:rw
    #   - /sys:/sys:ro
      # - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - back-tier
    restart: always

  # SERVICIO DE PROM2TEAMS - PARA ENVIAR ALERTAS A TEAMS
  prom2teams:
    container_name: prom2teams
    image: idealista/prom2teams:3.2.3
    restart: unless-stopped
    environment:
      PROM2TEAMS_CONNECTOR: "https://interbankpe.webhook.office.com/webhookb2/c5e36976-0e9a-4fe1-8e7f-b885310b115c@360bc517-7aac-4c17-9907-4c5f13a12289/IncomingWebhook/1cfdb84f13f84b5f904adeb24e9bd071/c75235ae-9234-4357-aeea-5e1682272cd0"
    ports:
      - 8089:8089
    networks:
      - back-tier
