version: "3.7"

networks:
  front-tier:
  back-tier:

volumes:
  prometheus-data: {}
  grafana-data: {}
  
services:

  # SERVICIO DE GRAFANA
  grafana:
    container_name: grafana
    image: grafana/grafana:11.0.0
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana-data/:/etc/grafana/provisioning/
      - grafana-data:/var/lib/grafana
    networks:
      - back-tier
      - front-tier
    restart: always

  # SERVICIO DE PROMETHEUS
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.34.0
    volumes:
      - ./prometheus-data/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - alertmanager:alertmanager
    networks:
      - back-tier
    restart: always

